project:
  type: website
  output-dir: docs

website:
  title: "Roberts Lab Course Set - Things u should know"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

  sidebar:
    style: "docked"
    search: true
    contents:
      - modules/00-markdown.qmd
      - modules/01-github.qmd
      - modules/02-bash.qmd
      - modules/03-rstudio.qmd
  


    
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true

editor: visual

